name: Issues Event
on: issues
jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Display event data
        run: echo ${{ toJSON(github.event) }}
      - name: Check out the repository
        uses: actions/checkout@v2
      - name: Create issue comment
        uses: peter-evans/create-issue-comment@v1
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            Thank you for opening this issue!
            We will look into it as soon as possible.
